/**
 * PDF Generation Service
 * Converts Markdown content into PDF buffers using PDFKit.
 */

import PDFDocument from "pdfkit";

/**
 * Generates a PDF from Markdown-like text content.
 * Returns a Buffer containing the PDF data.
 */
export function generatePDF(
    title: string,
    content: string,
    metadata?: { author?: string; subject?: string }
): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Title: title,
                Author: metadata?.author || "BlueprintAI",
                Subject: metadata?.subject || "AI-Generated Document",
            },
        });

        const chunks: Buffer[] = [];
        doc.on("data", (chunk: Buffer) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        // --- Cover Page ---
        doc.fontSize(32).fillColor("#00B8FF").text(title, { align: "center" });
        doc.moveDown(1);
        doc.fontSize(14).fillColor("#888888").text("Generated by BlueprintAI", {
            align: "center",
        });
        doc.fontSize(12).text(new Date().toLocaleDateString(), { align: "center" });
        doc.addPage();

        // --- Content ---
        const lines = content.split("\n");
        for (const line of lines) {
            if (line.startsWith("# ")) {
                doc.moveDown(1);
                doc.fontSize(22).fillColor("#00B8FF").text(line.replace("# ", ""));
                doc.moveDown(0.5);
            } else if (line.startsWith("## ")) {
                doc.moveDown(0.8);
                doc.fontSize(18).fillColor("#333333").text(line.replace("## ", ""));
                doc.moveDown(0.3);
            } else if (line.startsWith("### ")) {
                doc.moveDown(0.5);
                doc.fontSize(15).fillColor("#555555").text(line.replace("### ", ""));
                doc.moveDown(0.2);
            } else if (line.startsWith("- ") || line.startsWith("* ")) {
                doc.fontSize(11).fillColor("#222222").text(`  •  ${line.slice(2)}`, {
                    indent: 15,
                });
            } else if (line.match(/^\d+\.\s/)) {
                doc.fontSize(11).fillColor("#222222").text(`  ${line}`, { indent: 15 });
            } else if (line.startsWith("```")) {
                // Skip code fence markers
            } else if (line.startsWith("|")) {
                // Render table rows as plain text (simplified)
                doc.fontSize(10).fillColor("#444444").font("Courier").text(line);
                doc.font("Helvetica");
            } else if (line.trim() === "") {
                doc.moveDown(0.3);
            } else {
                doc.fontSize(11).fillColor("#222222").text(line, { align: "justify" });
            }
        }

        doc.end();
    });
}
